### ISSUE TITLE
Ed25519 to Curve25519 keys conversion

### ISSUE THREAD

**Issue by hadronzoo** [abstractj/kalium#19]
libsodium supports [Ed25519 to Curve25519 key conversion](http://doc.libsodium.org/advanced/ed25519-curve25519.html) with `crypto_sign_ed25519_pk_to_curve25519` and `crypto_sign_ed25519_sk_to_curve25519`. Could these functions be added to kalium?

**Comment by abstractj** [comment]
@hadronzoo I appreciate you took your time to raised this issue, but at the moment I swamped and can't implement it. Please make sure that every time you open an issue, also attach the PR with the changes you would like.

If you feel like you want to do this see my comments here: https://github.com/abstractj/kalium/pull/64

**Comment by blavenie** [comment]
@abstractj I have add a new PR for this issue. Can you review it ? :)

I can send you some coins of the crypto-currency Duniter G1 (www.duniter.org) for that :)  Just let me known.
