### ISSUE TITLE
crypto_auth/crypto_auth_verify are missing

### ISSUE THREAD

**Issue by joelrich** [abstractj/kalium#23]
Is there any reason why certain APIs like crypto_auth/crypto_auth_verify are missing?
Documentation: http://doc.libsodium.org/secret-key_cryptography/secret-key_authentication.html

**Comment by abstractj** [comment]
@joelrich landed here https://github.com/abstractj/kalium/commit/d8f5739122d241c6bfc10ce0a39d377d7787611e. Kudos to @erikswanson.

New release is coming.

**Comment by abstractj** [comment]
@joelrich @erikswanson version 0.4.0 was landed, just wait for sonatype to sync with Maven central. Have fun.
