### ISSUE TITLE
KeyPair copies&stores reference of byte array - dangerous side effects possible

### ISSUE THREAD

**Issue by franks42** [abstractj/kalium#27]
The KeyPair constructor simply assigns the references of the byte array for the publicKey and  secretKey member fields, and passes those references along to the PublicKey and PrivateKey constructors inside of the getPrivate/PublicKey methods.

As a result, the internal values of the publicKey and secretKey byte array element values can be changed outside of the scope of KeyPair, which can lead to "unexpected" results. 

At a minimum, a copy of the byte arrays should be stored and communicated. As the arrays are so short, that shouldn't affect performance, and make the KeyPar object immutable.

However, the whole use of byte arrays and strings for secrets should probably be revisited as mentioned in Issue-21...

Thanks, Frank.

**Comment by abstractj** [comment]
@franks42 sorry for the long delay Frank. Would you like to provide the source code to reproduce the issue? Would be helpful.

**Comment by franks42** [comment]
When you add the following snippet to "KeyPairTest.java", an exception will be thrown.

```java
    @Test
    public void testNoClonedKey() {
        try {
            byte[] rawKey = HEX.decode(BOB_PRIVATE_KEY);
            // remember the first byte of the private key
            byte b = rawKey[0];
            KeyPair kp = new KeyPair(rawKey);
            PrivateKey sk = kp.getPrivateKey();
            byte[] skb = sk.toBytes();
            // the exported private key should be the same as the original one
            assertTrue(b == skb[0]);
            // change the first byte of the original byte array
            rawKey[0] = 1;
            // that should not affect the private key inside of the KeyPair!!!
            assertTrue(b == skb[0]);
            // if exception, then either caller should be warned about this side effect, 
            // or we should clone the byte array after receiving it and make it immutable

        } catch (Exception e) {
            fail("Exception indicates that anyone holding on to the reference of the original private key, can change the byte array's content for all, which could be \"confusing\".");
        }
    }
```

It shows that you cannot reuse the byte array with the private key that was used in the KeyPair() constructor, otherwise it will affect all that share that reference.

Believe you should either warn the caller about this, or (my preference) clone the byte array inside the KeyPair() before you use it. The latter solution will essentially avoid any nasty side effects.
(The performance penalty for cloning is negligible for the 32bytes and all the computations associated with keypair generation.)

Hope this helps.
If you agree with the cloning approach, I'd be happy to provide a pull-request for the code changes.

**Comment by abstractj** [comment]
@franks42 thank you so much for spending time and raising this issue. I really appreciate it. However I don't have the time to implement this right now. So I would love if you raise the issue and provide a patch with the tests for the scenario you described.

Closing this issue for now, but feel free to reopen when you submit the patch.

Thank you.
