### ISSUE TITLE
KeyPair compatibility with SigningKey and VerifyKey

### ISSUE THREAD

**Issue by sclausen** [abstractj/kalium#33]
If I understand araight, `KeyPair` and `SigningKey`/`VerifyKey` are not compatible due to the different algorithms used in the methods `crypto_box_curve25519xsalsa20poly1305_keypair` and `crypto_sign_ed25519_seed_keypair`.
I want to prepare a KeyPair for a user which I later want to use to sign stuff always with the same `publicKey`, so am I right, that I'm forced to implement my own SigningKey(Pair) version with getters for `secretKey` and `publicKey`? Or may I haven't seen throught the difference between `secretKey` and `privateKey` or missed something else?

**Comment by franks42** [comment]
Hi Sebastian,

There are conversion formulas to "translate" curve25519 to ed25519, and vice versa.

As far as i can tell, lib sodium implemented the ed25519 to curve25519 conversion - see section" Advanced/ ed25519 to curve25519 conversion” of the manual.

It describes the crypto_sign_ed25519_pk_to_curve25519() and crypto_sign_ed25519_sk_to_curve25519() functions.

So if you start with the ed25519 signing key-pair, you can obtain your curve25519 encryption/dh-keys from them.

-FS.

**Comment by sclausen** [comment]
That's really nice! Could you provide an example, source or suggest something I could google? Unfortunately I don't kno what I should search for.

**Comment by sclausen** [comment]
Hi Frank,

unfortunately the section "Advanced/ ed25519 to curve25519 conversion" 
just tells how to use it in libsodium, but is there any solution with 
kalium?
I see, that I can obtain curve25519 encryption/dh-keys from a ed25519 
signing key-pair, but is there, except for the algorithm, any difference?
Is there a reason that sometime its privatekey/publickey and sometimes 
secretkey/publickey? And is there a reason, why in Kalium and 
SigningKey.class, the publicKey isn't a field and the secretKey is 
private without any getter?
I don't think my usecase is very special, so I have the strong feeling, 
that I'm missing something :-[

Thanks and thanks in advance for your help!

-- 
Kind regards
Mit freundlichen Grüßen
Sebastian Clausen

**Comment by franks42** [comment]
> unfortunately the section "Advanced/ ed25519 to curve25519 conversion”  
> just tells how to use it in libsodium, but is there any solution with 
> kalium?

Well… kalium is based on libsodium and Bruno Oliveira is actively developing it. 
Although most of the libsodium java-abstractions are implemented, there are still a few left to do, which includes the ones you need.

If you ask him nicely… and defend your use case… or better: provide the code, 
Bruno could add it to Kalium.

> I see, that I can obtain curve25519 encryption/dh-keys from a ed25519 
> signing key-pair, but is there, except for the algorithm, any difference?

No.

> Is there a reason that sometime its privatekey/publickey and sometimes 
> secretkey/publickey?

Believe the only reason is that the two letter abbreviation of public and private key is both “pk”,
which makes it easier to use the name secret-key such that you have “pk” and “sk”.

No “real” difference.

> And is there a reason, why in Kalium and 
> SigningKey.class, the publicKey isn't a field and the secretKey is 
> private without any getter?

Probably Bruno’s design decision to make it more difficult to get to the signing, i.e. private key, because it’s… private ;-).

> I don't think my usecase is very special, so I have the strong feeling, 
> that I'm missing something :-[

Notice that in general it’s better to have separate keys for signing and encryption… which is probably the reason why it is/was low on Bruno’s priority list (?).

-FS.


> On 18.08.2015 02:06, FrankS wrote:
> > Hi Sebastian,
> >
> > There are conversion formulas to "translate" curve25519 to ed25519, 
> > and vice versa.
> >
> > As far as i can tell, lib sodium implemented the ed25519 to curve25519 
> > conversion - see section" Advanced/ ed25519 to curve25519 conversion” 
> > of the manual.
> >
> > It describes the crypto_sign_ed25519_pk_to_curve25519() and 
> > crypto_sign_ed25519_sk_to_curve25519() functions.
> >
> > So if you start with the ed25519 signing key-pair, you can obtain your 
> > curve25519 encryption/dh-keys from them.
> >
> > -FS.
> >
> >
> > > On Aug 17, 2015, at 4:10 PM, Sebastian Clausen

**Comment by sclausen** [comment]
Thanks Frank! Many, many thanks for your explanation!
