### ISSUE TITLE
extended NaCl.java

### ISSUE THREAD

**Issue by franks42** [abstractj/kalium#34]
No issue - just a pointer to a equivalent NaCl.java file that I have been using for my naclj clojure project:

"https://github.com/franks42/naclj/blob/master/src-java/com/github/franks42/naclj/NaCl.java"

I've taken your original NaCl.java file and added a few more ffi interfaces. (Pretty much) all of them are tested in my clojure code and "should just work".

Furthermore, I got rid of the hard-coded constants and replaced them with interfaces to libsodium's function calls to get the same values. Do not believe those constants will change any time soon, but using the functions should make it easier to stay in sync with libsodium.

As I borrowed/stole/copied your initial work, I hope I can pay you back a little when you do the same for some of the additions.

Thanks!
-Frank.

**Comment by abstractj** [comment]
@franks42 thanks for the positive feedback Frank and I'm happy that it helped you. I will take into consideration your project, but feel free to send any pull requests or improvements.
