### ISSUE TITLE
NPE in Util.checkLength

### ISSUE THREAD

**Issue by wsargent** [abstractj/kalium#36]
```
 public static void checkLength(byte[] data, int size) {
        if (data == null || data.length != size)
            throw new RuntimeException("Invalid size: " + data.length);
}
```

https://github.com/abstractj/kalium/blob/master/src/main/java/org/abstractj/kalium/crypto/Util.java#L36

If data is null, then an NPE will be thrown instead of the runtime exception with the invalid size.

**Comment by abstractj** [comment]
@wsargent thanks for pointing this. Fixed here https://github.com/abstractj/kalium/commit/5b0e6cb0525c182886f4b89206230d9aeb3ec0af

To be released on Alpha version.
