### ISSUE TITLE
NaCl.Sodium.SECRETKEY_BYTES differs from the value in native header

### ISSUE THREAD

**Issue by davidkazlauskas** [abstractj/kalium#37]
crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES is defined as 32U, crypto_sign_ed25519_SECRETKEYBYTES is defined as 32U + 32U in native header, however in NaCl.Sodium static constants there's only one variable SECRETKEY_BYTES and it is defined as 32. This is confusing and can waste a lot of time if you're using native functions such as crypto_sign_ed25519_seed_keypair where buffer should be 64 bytes length.

IMO, there should be functions exposed giving secret key sizes also, like crypto_sign_ed25519_secretkeybytes or more constants provided in NaCl.Sodium class for the specific cryptography functions.

**Comment by abstractj** [comment]
@davidkazlauskas I think the latest changes introduced by @bendoerr help to clarify your question https://github.com/abstractj/kalium/commit/7aae0dccb6fe12486991e86dfc862668c9066f78.

Do you think this issue can be closed?

**Comment by davidkazlauskas** [comment]
Yeah, sure, I see there were added more specific constants to sources. As long as there's no ambiguity and constants are correct it should be okay.
