### ISSUE TITLE
Add support for crypto_box_{before,after}nm

### ISSUE THREAD

**Issue by iphydf** [abstractj/kalium#38]
Shared key generation is expensive. As an optimisation, we should have wrappers for the precomputation interface: http://nacl.cr.yp.to/box.html

**Comment by cch1** [comment]
+1.  I need this optimization as well.

**Comment by bendoerr** [comment]
I recently submitted PR https://github.com/abstractj/kalium/pull/44 that adds this feature.

**Comment by alias1** [comment]
Since #44 seems to be merged, this can probably be closed?

**Comment by abstractj** [comment]
@iphydf seems like what you want was already done by @bendoerr. If there's something missing, please file a new issue adding the code with the changes you would like to see.
