### ISSUE TITLE
crypto_auth still missing 

### ISSUE THREAD

**Issue by wsargent** [abstractj/kalium#40]
A search of Kalium shows:

```
➜  kalium git:(master) ag crypto_auth
src/main/java/org/abstractj/kalium/keys/AuthenticationKey.java
44:        sodium().crypto_auth_hmacsha512256(mac, message, message.length, key);
55:        return isValid(sodium().crypto_auth_hmacsha512256_verify(signature, message, message.length, key), "signature was forged or corrupted");

src/main/java/org/abstractj/kalium/NaCl.java
67:        public int crypto_auth_hmacsha512256(@Out byte[] mac, @In byte[] message, @u_int64_t long sizeof, @In byte[] key);
69:        public int crypto_auth_hmacsha512256_verify(@In byte[] mac, @In byte[] message, @u_int64_t long sizeof, @In byte[] key);
```

This was raised previously in https://github.com/abstractj/kalium/issues/23 and I believe that it's still open: the crypto_auth / crypto_auth_verify methods are not available through Kalium.

This was partially addressed in with the HMAC-SHA512 support in https://github.com/erikswanson/kalium/commit/94a31fafa77c38e37ffc66f9d9c0b7512eee8893 --  but this isn't crypto_auth as defined in https://download.libsodium.org/doc/secret-key_cryptography/secret-key_authentication.html though!  This is https://download.libsodium.org/doc/advanced/hmac-sha2.html and the documentation says:

> "Only use these functions for interoperability with 3rd party services. For everything else, you should probably use crypto_auth_detached()/crypto_auth_verify_detached() or crypto_generichash_*() instead."

As such, you can't really interop between other libsodium libraries and kalium, as anyone using crypto_auth can't then verify with Kalium.

**Comment by abstractj** [comment]
@wsargent will be very welcome if you submit a pull-request if you already know. Otherwise I will look at this as my time permits.

But thanks for pointing this.

**Comment by bendoerr** [comment]
@wsargent this may have changed since you wrote it, but currently `crypto_auth` is  `crypto_auth_hmacsha512256`. 
(https://github.com/jedisct1/libsodium/blob/1.0.8/src/libsodium/crypto_auth/crypto_auth.c#L26). 

Kalium provides both `crypto_auth` and `crypto_auth_verify` as their more full names `crypto_auth_hmacsha512256` and `crypto_auth_hmacsha512256_verify` per issue https://github.com/abstractj/kalium/issues/23 and PR https://github.com/abstractj/kalium/pull/28. I think this issue can be closed.

**Comment by wsargent** [comment]
@bendoerr Ah, okay -- so in libsodium, "crypto_auth" is the generic alias and crypto_auth_hmacsha512256 is the full implementation -- that's not made clear in https://download.libsodium.org/doc/secret-key_cryptography/secret-key_authentication.html.  Closing.
