### ISSUE TITLE
Including natives in release?

### ISSUE THREAD

**Issue by tcha8595** [abstractj/kalium#43]
Hi, possible to include natives for the platforms as part of the release?

This will be really handy.

**Comment by wsargent** [comment]
This is something that the Akka / Kamon team has implemented using a "native" dependency in Maven and a special project to manage Sigar:

https://github.com/kamon-io/sigar-loader/tree/master/core/src/main/resources

**Comment by abstractj** [comment]
@tcha8595 why? Unless you have an argument about it, I don't see a reason for it. Libsodium is available in most of the platforms, plus, you can include natives at lib folder of your own project.

**Comment by SummerStorm** [comment]
@abstractj In my case I'm using Amazon Lambda where all the dependencies must be inside the jar I upload since I don't have access to the underlying platform. 

Yes, I can include the natives in my lib folder, but I shouldn't have to since libsodium is a dependency of kalium, not my project.

**Comment by bendoerr** [comment]
Libsodium doesn't release native binaries so I don't think Kalium should include them. I might be wrong, but I thought Libsodium will choose the best/fastest implementation for a system at compile time, so it's always best to compile on the target system.

Maybe a good compromise would be to include a maven profile that makes it easier for folks to build and package a native for themselves?

**Comment by abstractj** [comment]
@SummerStorm I'm very sorry but it's not my goal to maintain any native code from Libsodium, but you are welcome to submit any suggestions. I'm closing it for now, unless this is a complete blocker, feel free to reopen and submit the changes.

@bendoerr I appreciate your ideas, but I don't see how this would not end with us maintaining a fork of libsodium. But feel free to create a feature request with your suggestion, or just submit a PR for discussion.

@wsargent we don't have the same thing, but today is Kalium will look at these folders https://github.com/abstractj/kalium/blob/master/src/main/java/org/abstractj/kalium/NaCl.java#L37-L39. Like I said to Ben, feel free to open a feature request or just send the suggested changes.

Thank you
