### ISSUE TITLE
Util.isValid should throw specific exception type

### ISSUE THREAD

**Issue by wsargent** [abstractj/kalium#50]
If the encryption / decryption fails on SecretBox, then Util.isValid is called -- this throws RuntimeException.

https://github.com/abstractj/kalium/blob/master/src/main/java/org/abstractj/kalium/crypto/Util.java#L46

Because RuntimeException is so general, if I want to catch this specific exception I have to check the message:

https://github.com/wsargent/play-kalium/blob/master/app/controllers/HomeController.scala#L25

This is not good -- there should be a specific `EncryptionFailedException` that extends from RuntimeException that can be checked individually.

**Comment by yusefnapora** [comment]
I don't understand why `isValid` throws at all?  I was definitely expecting it to return `true` or `false`, but instead it returns `true` or "blow up the JVM" :smile:

**Comment by bendoerr** [comment]
I'm on the fence about using a more specific exception for isValid, however I am much less enthusiastic about a boolean return, it's too easy to forget to check which I've been guilty of when using libSodium. 

My thought is that if you have a specific exception for isValid which you handle one way and then don't handle all runtime exceptions the same way it could reveal to an attacker something about the Kalium specific implementation that could give them a heads up. If there is a bug in the Kalium code, it really should just look like a decryption failure. It's a "fail closed" sort of mentality. @wsargent in your example why wouldn't you treat an NPE or other runtime exception similar to your decryption exception?

**Comment by wsargent** [comment]
Because I want to log it specifically as a decryption exception with an SLF4J marker, and it’s much harder to do with no type information.

Will.

**Comment by alias1** [comment]
I'm inclined to agree that being able to handle it 'specifically' is a good idea. What we expose back to the user (eg. generic error message) should be up to the individual developer/app requirements.

**Comment by abstractj** [comment]
@wsargent thank you so much for spending time bringing this up. I really appreciate it. However I do not think this is something I would like to add right now, nor have the time for this. It's pretty much possible to handle such exception as is. 

But if you really want to see this into the codebase, please raise a PR with a clear explanation why you need this and ping the others involved for discussion/review.

Thank you.

**Comment by wsargent** [comment]
That's fine -- I think https://github.com/google/tink/ may be a better pure Java fit for my needs.
