### ISSUE TITLE
Added play-kalium example project

### ISSUE THREAD

**Issue by wsargent** [abstractj/kalium#51]
I wrote up a simple project showing Play and Kalium working together.

https://github.com/wsargent/play-kalium

Is there a documentation place for Kalium projects?

**Comment by abstractj** [comment]
@wsargent awesome! Currently I really suck at documentation due to my limited time (I hope to fix it), but we have something here https://github.com/abstractj/kalium/tree/gh-pages and the hosted page here: http://abstractj.github.io/kalium/. There's a lot to improve, but I'm open to suggestions.

**Comment by abstractj** [comment]
@wsargent I think we can close this, but feel free to reopen if I'm completely wrong.

**Comment by wsargent** [comment]
I have seen https://github.com/abstractj/kalium/blob/gh-pages/index.html -- if that's what we've got, then I'll work from there and submit a PR.
