### ISSUE TITLE
Version 1.0.10 of libsodium is cannot be used due to version check

### ISSUE THREAD

**Issue by bendoerr** [abstractj/kalium#52]
A simple compare against the version string is insufficient as `"1.0.10".compareTo("1.0.3") == -1`. I'm curious of other's thoughts on the need for this check.

**Comment by neuhaus** [comment]
It's not just a matter of changing the version string I believe. There are new functions that have been added to the library.

**Comment by abstractj** [comment]
@bendoerr I've included this to not go crazy supporting whatever libsodium version :) But let me know if you have any other ideas.

Closing it, once it was already landed.
