### ISSUE TITLE
Release Kalium next week

### ISSUE THREAD

**Issue by abstractj** [abstractj/kalium#61]
Ahoy, I would like to cut a new release of Kalium (0.5.0) next week and remove Alpha suffix. @lvh @wsargent @bendoerr I know that you guys have projects depending on Kalium, if you have any strong feelings about it, let me know.

I would like to save 1.0.0 [these changes](https://github.com/abstractj/kalium/pull/48) in.

**Comment by lvh** [comment]
This looks good to me :) (FYI: caesium no longer depends on kalium so that I can experiment more easily with bindings.)

**Comment by wsargent** [comment]
I'm all good, it's an example project.

**Comment by bendoerr** [comment]
Go for it!
