### ISSUE TITLE
Have to rename libsodium.dll -> sodium.dll so that jnr-ffi could find library

### ISSUE THREAD

**Issue by nartamonov** [abstractj/kalium#65]
Hi! I downloaded latest release of libsodium (https://download.libsodium.org/libsodium/releases/libsodium-1.0.11-msvc.zip), extracted appropriate `libsodium.dll`, set up `java.library.path` property... but jnr-ffi failed to load sodium library (throws LinkageError). If I rename `libsodium.dll` to `sodium.dll` it works fine. Is it correct behaviour on Windows platform?

OS: Windows 7 SP1 x86
Kalium 0.5.0

**Comment by buddhabuddy** [comment]
Also on windows 10 I had a similar error:
Caused by: java.lang.UnsatisfiedLinkError: unknown
        at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)

Using procmon I found it was looking for libsodium not in the java library path but in one spot:
C:\ProgramData\Oracle\Java\javapath\sodium.dll

I took libsodium-1.0.11-msvc\x64\Release\v140\dynamic\libsodium.dll copied and renamed it to the path and now the play-kalium example runs :)

**Comment by niteshgarg** [comment]
I also got same problem in windows 7.

Exception in thread "main" java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)

I also tried the solutions provided above but still it gives the same error.  Not sure what is the issue. 
Kindly check and get back. 

Thanks
Nitesh

**Comment by buddhabuddy** [comment]
Nitesh you'll need to procmon and find out where its looking for the dll...

**Comment by thclev** [comment]
This looks like expected behavior? Code looks for "sodium" as the library name.

**Comment by abstractj** [comment]
@nartamonov actually Kalium look at these folders https://github.com/abstractj/kalium/blob/master/src/main/java/org/abstractj/kalium/NaCl.java#L37-L40. So in the worst case scenario, you can create a `lib` folder inside your project and find it.

I just installed the latest version of libsodium 1.0.11-1 and all the tests are green to me.

I'm sorry but I'm completely clueless about Windows environment, but if you have any suggestions or PR changes. They will be more than welcome.
