### ISSUE TITLE
v0.5.0?

### ISSUE THREAD

**Issue by alias1** [abstractj/kalium#67]
Looking at the tags, I can see `0.5.0`, but the README stills says to use `0.4.0`

Is it safe to assume that `0.5.0` is the latest, and the README is just out of date?

**Comment by abstractj** [comment]
@alias1 look here http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.abstractj.kalium%22%20AND%20a%3A%22kalium%22
