### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found

### ISSUE THREAD

**Issue by huskarl-sun** [abstractj/kalium#75]
I found lots of crash only below android 4.4，the exception like：
java.lang.UnsatisfiedLinkError: Native method not found: org.abstractj.kalium.SodiumJNI.crypto_aead_chacha20poly1305_encrypt:([BI[I[BI[BI[B[B[B)I
	at org.abstractj.kalium.SodiumJNI.crypto_aead_chacha20poly1305_encrypt(SodiumJNI.java)

**Comment by abstractj** [comment]
@huskarl-sun please reporte this to Kalium JNI (https://github.com/hbmartin/kalium-jni). This project does not support Android
