### ISSUE TITLE
java.lang.NoClassDefFoundError: jnr/ffi/Platform$OS

### ISSUE THREAD

**Issue by florianschneider** [abstractj/kalium#79]
Just added a maven dependency to Kalium to my project
```
<dependency>
			<groupId>org.abstractj.kalium</groupId>
			<artifactId>kalium</artifactId>
			<version>0.6.0</version>
		</dependency>
```

Attempting to use the framework, I'm running into the following exception: 

```
java.lang.NoClassDefFoundError: jnr/ffi/Platform$OS
	at org.abstractj.kalium.NaCl$1.<clinit>(NaCl.java:37) ~[kalium-0.6.0.jar:na]
	at org.abstractj.kalium.NaCl.libraryName(NaCl.java:37) ~[kalium-0.6.0.jar:na]
	at org.abstractj.kalium.NaCl.<clinit>(NaCl.java:34) ~[kalium-0.6.0.jar:na]
	at org.abstractj.kalium.crypto.Password.verify(Password.java:35) ~[kalium-0.6.0.jar:na]
```

Do I have to bundle any DLL of sodium with my application? I was hoping you would package that for me with the Kalium jar file.

Cheers,
Florian

**Comment by arvindsinghtomar** [comment]
I am having the same error .Any solution??

**Comment by florianschneider** [comment]
As it seems, you have to include the DLL for yourself with your application. 

Please anybody correct me if I'm wrong - to the best of my recently gained knowledge, it would be possible to bundle the dll with the library jar, but then the library would have to copy it to a temporary folder and load it via a System call.

**Comment by abstractj** [comment]
@florianschneider no, we're not going to bundle DLLs inside the project. But you are free to do by yourself if you want to.

@arvindsinghtomar I'm sorry, but I don't have any solution. I have no idea about Windows and DLLs.

**Comment by arvindsinghtomar** [comment]
@abstractj  I am not using it in windows. I am using it in android platform.

**Comment by abstractj** [comment]
@arvindsinghtomar https://github.com/abstractj/kalium#faq

**Comment by agarbutt** [comment]
I have created PR #81 that suggests documentation for installing `libsodium` on Windows for use by the Kalium artifact.
